name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: call-build
    strategy:
      matrix:
        configuration: [Debug, Release]
    uses: codebeltnet/jobs-dotnet-build/.github/workflows/default.yml@v3
    with:
      projects: src/**/*.csproj
      configuration: ${{ matrix.configuration }}

  test:
    name: call-test
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        os: [ubuntu-24.04, windows-2025, macos-26]
    uses: codebeltnet/jobs-dotnet-test/.github/workflows/default.yml@v3
    with:
      projects: test/**/*.csproj
      configuration: ${{ matrix.configuration }}
      runs-on: ${{ matrix.os }}
      verbosity-level: normal
      restore: true
      build: true
